### ISSUE TITLE
mac safari 7.1: facebook like & share buttons are too small

### ISSUE THREAD

**Issue by BarboraDoslikova** [BarboraDoslikova/teace.ca#5]
find out: how to fix this? maybe @radekstepan knows?

**Comment by radekstepan** [comment]
``` css
.pluginButton {
  border-radius: 4px;
  padding: 4px;
}
```
